# Generated by Django 2.2.14 on 2020-07-04 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='add',
            new_name='Todo',
        ),
        migrations.RenameField(
            model_name='todo',
            old_name='task',
            new_name='text',
        ),
    ]
