# Generated by Django 2.2.13 on 2020-07-01 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='add',
            name='complete',
            field=models.BooleanField(default=False),
        ),
    ]
